language: r
cache: packages

notifications:
  email:
    on_success: change
    on_failure: change

branches:
  except:
    - gh-pages

before_install:
  - echo "options(repos = c(CRAN = 'https://packagemanager.rstudio.com/all/__linux__/xenial/latest'))" >> ~/.Rprofile.site
  - echo "options(HTTPUserAgent = paste0('R/', getRversion(), ' R (', paste(getRversion(), R.version['platform'], R.version['arch'], R.version['os']),')'))" >> ~/.Rprofile.site

script:
  - Rscript -e "library('tidyverse')"
  - make html

after_success:
  - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
